In [1]:
import numpy as np

creating an array using numpy and a list. 

In [4]:
my_arr = np.arange(100000)
print(my_arr)


[    0     1     2 ... 99997 99998 99999]


In [7]:
my_list = list(range(100000))

showing the time the difference between numpy and python's counterpart. numpy is faster.

In [8]:
%time for _ in range(10): mr_arr2 = my_arr * 2

Wall time: 1.99 ms


In [9]:
%time for _ in range(10): [x*2 for x in my_list]

Wall time: 58.5 ms


creating 2d arrays using numpy

In [10]:
data = np.random.randn(2,3)

In [11]:
data

array([[-1.3689469 ,  0.05632661, -0.56990631],
       [-0.40885936,  0.18815008, -1.00479615]])

doing math with 2d array. the 10 is going to be multiplied with each element on the array

In [12]:
data * 10

array([[-13.68946897,   0.56326606,  -5.69906309],
       [ -4.08859364,   1.8815008 , -10.0479615 ]])

able to add 2 arrays with each other

In [14]:
data + data

array([[-2.73789379,  0.11265321, -1.13981262],
       [-0.81771873,  0.37630016, -2.0095923 ]])

gets the shape of the array. it can be like a matrix 

In [15]:
data.shape

(2, 3)

prints the type of the array

In [16]:
data.dtype

dtype('float64')

to create an array we would us the array function. it accepts any sequence like object and produces a new NumPy array containing the data.