In [1]:
import numpy as np

creating an array using numpy and a list. 

In [2]:
my_arr = np.arange(100000)
print(my_arr)


[    0     1     2 ... 99997 99998 99999]


In [3]:
my_list = list(range(100000))

showing the time the difference between numpy and python's counterpart. numpy is faster.

In [4]:
%time for _ in range(10): mr_arr2 = my_arr * 2
%time for _ in range(10): [x*2 for x in my_list]

Wall time: 999 µs
Wall time: 61 ms


creating 2d arrays using numpy

In [5]:
data = np.random.randn(2,3)

In [6]:
data

array([[ 0.28982563, -0.60968987,  0.04200788],
       [-0.18955216, -0.1942397 ,  0.90812454]])

doing math with 2d array. the 10 is going to be multiplied with each element on the array

In [7]:
data * 10

array([[ 2.89825634, -6.09689869,  0.42007883],
       [-1.89552157, -1.94239703,  9.08124537]])

able to add 2 arrays with each other

In [8]:
data + data

array([[ 0.57965127, -1.21937974,  0.08401577],
       [-0.37910431, -0.38847941,  1.81624907]])

gets the shape of the array. it can be like a matrix 

In [9]:
data.shape

(2, 3)

prints the type of the array

In [10]:
data.dtype

dtype('float64')

to create an array we would us the array function. it accepts any sequence like object and produces a new NumPy array containing the data.

In [11]:
data1 = [6,7.5,8,0,1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# shows the dimensions from the data
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In addition to np.array, there are a number of other functions for creating new
arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
given length or shape. empty creates an array without initializing its values to any par‐
ticular value. To create a higher dimensional array with these methods, pass a tuple
for the shape:

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# it's not safe to assume that np/empty is going to return an arraay of all
# zeros. we might get some "gargbage" values
np.empty((2,3,2))

array([[[1.05168057e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.06099790e-312, 6.93642604e+169]],

       [[9.13446327e+169, 5.53809886e+174],
        [9.30775512e+165, 3.34653297e-061],
        [6.15888008e+170, 1.13004060e-042]]])

In [24]:
# arrage is an arrary-value version of the built-in python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Function Description
array Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype
or explicitly specifying a dtype; copies the input data by default
asarray Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list
ones, 
ones_like
Produce an array of all 1s with the given shape and dtype; ones_like takes another array and
produces a ones array of the same shape and dtype
zeros, 
zeros_like
Like ones and ones_like but producing arrays of 0s instead
empty, 
empty_like
Create new arrays by allocating new memory, but do not populate with any values like ones and
zeros
full, 
full_like
Produce an array of the given shape and dtype with all values set to the indicated “fill value”
full_like takes another array and produces a filled array of the same shape and dtype
eye, identity Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

Data types for ndarrays
The data type or dtype is a special object containing the information (or metadata,data about data) the ndarray needs to interpret a chunk of memory as a particular
type of data:

In [25]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [26]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [27]:
arr1.dtype


dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

we can type cast the array using the .astype function with type we want to convert to.

In [29]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [30]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

we can have a array of strings and convert them into numeric form

In [32]:
numeric_strings = np.array(['1.25','-9.8','42'],dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.8 , 42.  ])

In [33]:
int_array = np.arange(10)

In [34]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [35]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

doing arithmetic with Numpy arrays
arrays are important because they enable you to express batch operations on data without writing any for loops. Numpy users call this vectorization. Any arithmetic operations between equal size arrays applies the operation element wise

In [37]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [38]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
# multipling 
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
# subtracting
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

scalaring operations

In [41]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [44]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [45]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Basic Indexing and Slicing

In [46]:
arr = np.arange(10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[5]

5

In [49]:
# looks like the same way python does slicing
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8] = 12

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection.An important first dis‐tinction from Python’s built-in lists is that array slices are views on the original array.This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [52]:
arr_slice = arr[5:8]

In [53]:
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[1] = 12345

In [55]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [56]:
# the 'bare' slice [:] will assign all values
arr_slice[:] = 64

if we want a copy we would have to tell numpy that we want a copy by saying: [5:8].copy().

In [57]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

playing with 2d arrays

In [58]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
arr2d[1]

array([4, 5, 6])

In [60]:
arr2d[0][2]

3

In [61]:
arr2d[1,2]

6

In [62]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [63]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
old_values = arr3d[0].copy()

In [66]:
arr3d[0] = 42

In [67]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[0]=old_values

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

we can form a 1d array the same way we slice 

In [70]:
arr3d[1,0]

array([7, 8, 9])

In [71]:
x = arr3d[1]

In [72]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
x[0]

array([7, 8, 9])

Indexing with slices

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [76]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# can slice multiple indexes
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
arr2d[:2,2]

array([3, 6])

In [80]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

Boolean indexing

In [81]:
names = np.array(['Bob',"Joe","Will","Bob",'Will','Joe','Joe'])

In [82]:
data = np.random.randn(7,4)

In [83]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [84]:
data

array([[ 0.86505435,  0.7097498 , -0.36763799,  0.1920679 ],
       [-1.26611118, -0.58648172,  0.49457446, -1.65019227],
       [-1.90174902,  0.5516243 ,  1.39012387,  0.39851379],
       [ 0.51524845, -0.32205619,  2.13638483,  0.70950217],
       [ 0.32912703,  0.48046848,  0.48115192, -1.87159601],
       [ 0.38640381, -1.01500386, -1.78392047, -1.60384022],
       [ 0.21087002,  0.3900695 , -0.99067905,  0.60288478]])

In [85]:
# creating a boolean array. we are able to use the '==' to make it
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [86]:
# we can pass a boolean array when indexing an array
data[names == 'Bob']


array([[ 0.86505435,  0.7097498 , -0.36763799,  0.1920679 ],
       [ 0.51524845, -0.32205619,  2.13638483,  0.70950217]])

In [87]:
# for it to work the array has to be the same size of the other array
data[names == 'Bob',2:]

array([[-0.36763799,  0.1920679 ],
       [ 2.13638483,  0.70950217]])

In [88]:
data[names == 'Bob',3]

array([0.1920679 , 0.70950217])

In [89]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [90]:
# to nagate the boolean array
data[~(names == 'Bob')]

array([[-1.26611118, -0.58648172,  0.49457446, -1.65019227],
       [-1.90174902,  0.5516243 ,  1.39012387,  0.39851379],
       [ 0.32912703,  0.48046848,  0.48115192, -1.87159601],
       [ 0.38640381, -1.01500386, -1.78392047, -1.60384022],
       [ 0.21087002,  0.3900695 , -0.99067905,  0.60288478]])

In [91]:
conda = names == 'Bob'

In [92]:
data[~conda]

array([[-1.26611118, -0.58648172,  0.49457446, -1.65019227],
       [-1.90174902,  0.5516243 ,  1.39012387,  0.39851379],
       [ 0.32912703,  0.48046848,  0.48115192, -1.87159601],
       [ 0.38640381, -1.01500386, -1.78392047, -1.60384022],
       [ 0.21087002,  0.3900695 , -0.99067905,  0.60288478]])

In [93]:
# have to use the boolean arithmetic operators like &(and) and |(or)
mask = (names == 'Bob') | (names == 'Will')

In [94]:
mask

array([ True, False,  True,  True,  True, False, False])

In [95]:
data[mask]

array([[ 0.86505435,  0.7097498 , -0.36763799,  0.1920679 ],
       [-1.90174902,  0.5516243 ,  1.39012387,  0.39851379],
       [ 0.51524845, -0.32205619,  2.13638483,  0.70950217],
       [ 0.32912703,  0.48046848,  0.48115192, -1.87159601]])

In [96]:
data[data<0]=0

In [97]:
data

array([[0.86505435, 0.7097498 , 0.        , 0.1920679 ],
       [0.        , 0.        , 0.49457446, 0.        ],
       [0.        , 0.5516243 , 1.39012387, 0.39851379],
       [0.51524845, 0.        , 2.13638483, 0.70950217],
       [0.32912703, 0.48046848, 0.48115192, 0.        ],
       [0.38640381, 0.        , 0.        , 0.        ],
       [0.21087002, 0.3900695 , 0.        , 0.60288478]])

In [98]:
data[names  != 'Joe'] = 7

In [99]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.49457446, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.38640381, 0.        , 0.        , 0.        ],
       [0.21087002, 0.3900695 , 0.        , 0.60288478]])

fancy indexing: a way to index using integer arrays

In [100]:
arr = np.empty((8,4))

In [101]:
for i in range(8):
    arr[i] = i

In [102]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order:

In [103]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [106]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [107]:
arr = np.arange(32).reshape((8,4))

In [108]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [109]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

Transposing array and swapping axes

In [110]:
arr = np.arange(15).reshape((3,5))

In [111]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
arr.T 

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [113]:
# we can do the dot product by using np.dot

arr = np.random.randn(6,3)

In [114]:
arr

array([[ 1.3695229 , -0.61203234, -0.71089204],
       [-1.15707704, -1.37616195, -0.80480655],
       [ 1.19217421,  1.27168301,  0.19585547],
       [-0.37785642, -1.04747076, -0.83096944],
       [-0.92812543,  0.34147237, -0.24917751],
       [-1.14215684,  1.36902128, -0.94190018]])

In [115]:
np.dot(arr.T,arr)

array([[6.94441415, 0.78542812, 1.81218696],
       [0.78542812, 6.97360061, 1.28754671],
       [1.81218696, 1.28754671, 2.83121602]])

In [116]:
# to transpose a higher dimensional array
arr = np.arange(16).reshape((2,2,4))

In [117]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [119]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Here, the axes have been reordered with the second axis first, the first axis second,
and the last axis unchanged.

Simple transposing with .T is a special case of swapping axes. ndarray has the method
swapaxes, which takes a pair of axis numbers and switches the indicated axes to rear‐
range the data:

In [120]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [121]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

Universal Functions: Fast Element-Wise Array

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.


In [122]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [124]:
np.exp(arr)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])

These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays
(thus, binary ufuncs) and return a single array as the result:

In [125]:
x = np.random.randn(8)
y = np.random.randn(8)

In [127]:
x

array([-0.88803191,  0.41131482, -0.55405289, -0.856328  ,  2.27465573,
       -0.66218334, -0.36556722, -0.30170844])

In [128]:
y

array([-1.50753047, -0.95645831,  1.26072483,  1.01849817, -0.08410164,
       -0.06978889, -0.91499862,  1.06245377])

In [129]:
# using maximum.
np.maximum(x,y)

array([-0.88803191,  0.41131482,  1.26072483,  1.01849817,  2.27465573,
       -0.06978889, -0.36556722,  1.06245377])